const data = {
    code: 0,
    data: {
        base: {
            avatarUrl: "/img/avatar.jpg",
            birthdayProcessSuccessYear: 0,
            cardNumber: "241031115916050001",
            city: "北京市",
            dateAdd: "2024-10-31 11:59:37",
            dateLogin: "2025-01-03 10:38:32",
            getLevelDate: "2024-10-31 11:59:38",
            id: 30496437,
            ipAdd: "121.35.2.235",
            ipLogin: "116.128.236.84",
            isFaceCheck: false,
            isIdcardCheck: false,
            isManager: false,
            isSeller: false,
            isSendRegisterCoupons: true,
            isShopManager: false,
            isTeamLeader: false,
            isTeamMember: false,
            isUserAttendant: false,
            lastOrderDate: "2025-01-03 10:43:54",
            levelId: 4201,
            levelRenew: false,
            mobile: "15320241031",
            mobileVisInvister: true,
            nick: "佩德罗",
            province: "北京市",
            pwd: "yes",
            referrerType: 0,
            secondsAfterRegister: 5525094,
            source: 9,
            sourceStr: "后台录入",
            status: 0,
            statusStr: "默认",
            taskUserLevelSendMonth: 202410,
            taskUserLevelSendPerMonth: false,
            taskUserLevelUpgrade: false,
            userId: 1605,
            username: "佩德罗",
        },
        ext: {},
        userLevel: {
            dateAdd: "2022-01-31 00:50:52",
            dateUpdate: "2022-02-04 12:26:53",
            defValidityUnit: 3,
            id: 4201,
            level: 3,
            name: "砖石",
            paixu: 0,
            rebate: 10,
            status: 0,
            upgradePayNumber: 0,
            upgradeScore: 0,
            userId: 1605,
        },
    },
    msg: "success",
};


export default eventHandler(async (event) => {
    return data
});
