const data = {
    code: 0,
    "data": {
        "extJson": {},
        "goods": [
            {
                "afterSale": "",
                "amount": 0.02,
                "amountCoupon": 0,
                "amountSingle": 0.01,
                "amountSingleBase": 0.01,
                "buyRewardEnd": false,
                "cardIsSend": false,
                "categoryId": 272693,
                "cyTableStatus": 1,
                "dateAdd": "2025-01-03 10:43:53",
                "fxType": 2,
                "goodsId": 157447,
                "goodsIdStr": "157447",
                "goodsName": "虚拟商品（购买时无需填写收货地址，无需物流）",
                "gotScore": 2000,
                "gotScoreSingle": 1000,
                "id": 8625834,
                "iotOpen": false,
                "isProcessHis": false,
                "isScoreOrder": false,
                "number": 2,
                "numberNoFahuo": 2,
                "orderId": 5705839,
                "persion": 0,
                "pic": "https://dcdn.it120.cc/2022/02/04/b5017470-29bb-43a3-b34c-56cdf6b0fb05.png",
                "propertyChildIds": "",
                "purchase": false,
                "refundStatus": 0,
                "reputationShow": true,
                "score": 0,
                "shopId": 0,
                "status": 1,
                "type": 0,
                "uid": 30496437,
                "unit": "件",
                "userId": 1605
            },
            {
                "afterSale": "0",
                "amount": 6,
                "amountCoupon": 0,
                "amountSingle": 1,
                "amountSingleBase": 1,
                "buyRewardEnd": false,
                "cardIsSend": false,
                "categoryId": 272693,
                "cyTableStatus": 1,
                "dateAdd": "2025-01-03 10:43:53",
                "fxType": 2,
                "goodsId": 1052000,
                "goodsIdStr": "1052000",
                "goodsName": "实物商品（购买时需填写收货地址，支持售后）",
                "gotScore": 3000,
                "gotScoreSingle": 500,
                "id": 8625835,
                "iotOpen": false,
                "isProcessHis": false,
                "isScoreOrder": false,
                "number": 6,
                "numberNoFahuo": 6,
                "orderId": 5705839,
                "persion": 0,
                "pic": "https://dcdn.it120.cc/2022/02/04/fa78ff5e-553f-40f2-8c78-b7ab8ed8bd39.png",
                "propertyChildIds": "",
                "purchase": false,
                "refundStatus": 0,
                "reputationShow": true,
                "score": 0,
                "shopId": 0,
                "status": 1,
                "type": 0,
                "uid": 30496437,
                "unit": "件",
                "userId": 1605
            }
        ],
        "logistics": {
            "address": "213",
            "areaStr": "东城区",
            "cityId": "110100",
            "cityStr": "-",
            "dateLastTrace": "2025-01-03 10:43:53",
            "dateUpdate": "2025-01-03 10:43:53",
            "districtId": "110101",
            "id": 5705839,
            "linkMan": "213",
            "linkManMask": "2*3",
            "mobile": "13637446500",
            "mobileMask": "136****6500",
            "needQuery": false,
            "provinceId": "110000",
            "provinceStr": "北京市",
            "status": -1,
            "streetId": "0",
            "type": 0,
            "uid": 30496437,
            "userId": 1605
        },
        "logs": [
            {
                "dateAdd": "2025-01-03 10:43:53",
                "id": 19386486,
                "orderId": 5705839,
                "type": 0,
                "typeStr": "下单",
                "uid": 30496437,
                "userId": 1605
            },
            {
                "dateAdd": "2025-01-03 10:43:53",
                "id": 19386487,
                "orderId": 5705839,
                "type": 1,
                "type2": 0,
                "typeStr": "支付",
                "uid": 30496437,
                "userId": 1605
            }
        ],
        "orderInfo": {
            "amount": 6.02,
            "amountCard": 0,
            "amountCoupons": 0,
            "amountLogistics": 0,
            "amountReal": 6.02,
            "amountRefundTotal": 0,
            "amountTax": 0,
            "amountTaxGst": 0,
            "amountTaxService": 0,
            "autoDeliverStatus": 0,
            "dateAdd": "2025-01-03 10:43:53",
            "dateClose": "2025-01-03 11:43:53",
            "datePay": "2025-01-03 10:43:53",
            "dateUpdate": "2025-01-03 10:43:53",
            "differHours": 0,
            "goodsNumber": 8,
            "gotScore": 5000,
            "hasRefund": false,
            "hoursToAppointmentTime": 0,
            "id": 5705839,
            "ip": "116.128.236.84",
            "isCanHx": false,
            "isDelUser": false,
            "isEnd": false,
            "isHasBenefit": false,
            "isNeedLogistics": true,
            "isPay": true,
            "isScoreOrder": false,
            "isSuccessPingtuan": false,
            "jd8Status": 0,
            "nearbyCloseMillis": 3599324,
            "orderNumber": "250103104316050002",
            "orderType": 0,
            "periodAutoPay": false,
            "pid": 0,
            "qudanhao": "0002",
            "refundStatus": 0,
            "remark": "",
            "score": 0,
            "scoreDeduction": 0,
            "shopId": 0,
            "status": 1,
            "statusStr": "待发货",
            "trips": 0,
            "type": 0,
            "uid": 30496437,
            "userId": 1605
        },
        "orderLogisticsShipperLogs": [],
        "orderLogisticsShippers": [],
        "user": {
            "avatarUrl": "https://dcdn.it120.cc/cuser/1605/2025/01/03/e2344408-6633-4631-813f-cdd015f220c7.jpg",
            "nick": "测试用户-1031"
        }
    },
    msg: "success",
};

export default eventHandler(async (event) => {
    return data;
});
