const data = {
    "code": 0,
    "data": {
        "result": [
            {
                "afterSale": "0,1,2",
                "categoryId": 37962,
                "characteristic": "相机全新升级 / 960帧超慢动作 / 手持超级夜景 / 全球首款双频GPS / 骁龙845处理器 / 红外人脸解锁 / AI变焦双摄 / 三星 AMOLED 屏",
                "commission": 0,
                "commissionSettleType": 0,
                "commissionType": 0,
                "commissionUserType": 0,
                "dateAdd": "2019-05-27 15:02:52",
                "dateUpdate": "2024-12-31 16:04:09",
                "fxType": 2,
                "gotScore": 0,
                "gotScoreType": 0,
                "hasAddition": false,
                "hasTourJourney": false,
                "hidden": 0,
                "id": 139133,
                "kanjia": false,
                "kanjiaPrice": 0,
                "limitation": false,
                "logisticsId": 0,
                "maxCoupons": 1,
                "miaosha": false,
                "minBuyNumber": 1,
                "minPrice": 2599,
                "minScore": 0,
                "name": "小米8[虚拟商品]",
                "numberFav": 27,
                "numberGoodReputation": 2,
                "numberOrders": 31,
                "numberReputation": 0,
                "numberSells": 120,
                "originalPrice": 2999,
                "overseas": false,
                "paixu": 0,
                "persion": 0,
                "pic": "https://cdn.it120.cc/apifactory/2019/06/20/9ebdb53d-aa8e-48e6-ba71-2dc8ceea3259.jpg",
                "pingtuan": false,
                "pingtuanPrice": 0,
                "propertyIds": ",13090,13093,",
                "recommendStatus": 0,
                "recommendStatusStr": "普通",
                "seckillBuyNumber": 0,
                "sellEnd": false,
                "sellStart": true,
                "shopId": 0,
                "status": 0,
                "statusStr": "上架",
                "storeAlert": false,
                "stores": 8,
                "stores0Unsale": false,
                "storesExt1": 0,
                "storesExt2": 0,
                "type": 0,
                "unusefulNumber": 0,
                "usefulNumber": 0,
                "userId": 1605,
                "vetStatus": 1,
                "views": 25179,
                "weight": 0
            },
            {
                "afterSale": "0,1,2",
                "categoryId": 37966,
                "characteristic": "第八代酷睿i7六核标压处理器 ／ 72%NTSC高色域窄边框全高清屏 ／ 256G高速固态 ／ 双烤不限频不降频／ 冷酷到底的散热系统",
                "commission": 0,
                "commissionSettleType": 0,
                "commissionType": 0,
                "commissionUserType": 0,
                "dateAdd": "2019-05-27 14:34:21",
                "dateUpdate": "2024-12-30 15:24:24",
                "fxType": 2,
                "gotScore": 0,
                "gotScoreType": 0,
                "hasAddition": false,
                "hasTourJourney": false,
                "hidden": 0,
                "id": 139100,
                "kanjia": false,
                "kanjiaPrice": 0,
                "limitation": false,
                "logisticsId": 4751,
                "maxCoupons": 1,
                "miaosha": false,
                "minBuyNumber": 1,
                "minPrice": 7999,
                "minScore": 0,
                "name": "小米游戏本[评价]",
                "numberFav": 38,
                "numberGoodReputation": 2,
                "numberOrders": 12,
                "numberReputation": 0,
                "numberSells": 21,
                "originalPrice": 8999,
                "overseas": false,
                "paixu": 0,
                "persion": 0,
                "pic": "https://cdn.it120.cc/apifactory/2019/06/20/6271e429-bd00-4def-8fff-05264e1f26d2.jpg",
                "pingtuan": false,
                "pingtuanPrice": 0,
                "propertyIds": ",13093,",
                "recommendStatus": 0,
                "recommendStatusStr": "普通",
                "seckillBuyNumber": 0,
                "sellEnd": false,
                "sellStart": true,
                "shopId": 0,
                "status": 0,
                "statusStr": "上架",
                "storeAlert": false,
                "stores": 39,
                "stores0Unsale": false,
                "storesExt1": 0,
                "storesExt2": 0,
                "type": 0,
                "unusefulNumber": 0,
                "usefulNumber": 0,
                "userId": 1605,
                "vetStatus": 1,
                "views": 21310,
                "weight": 0
            },
            {
                "afterSale": "0,1,2",
                "categoryId": 37962,
                "characteristic": "全息幻彩全曲面玻璃机身 / 骁龙855旗舰处理器 / 索尼4800万超广角微距三摄 / 20W无线闪充 / 第5代极速屏下指纹解锁",
                "commission": 0,
                "commissionSettleType": 0,
                "commissionType": 0,
                "commissionUserType": 0,
                "dateAdd": "2019-05-27 14:20:51",
                "dateUpdate": "2024-12-29 18:28:36",
                "fxType": 2,
                "gotScore": 0,
                "gotScoreType": 0,
                "hasAddition": false,
                "hasTourJourney": false,
                "hidden": 0,
                "id": 139088,
                "kanjia": true,
                "kanjiaPrice": 0,
                "limitation": false,
                "logisticsId": 4727,
                "maxCoupons": 1,
                "miaosha": false,
                "minBuyNumber": 1,
                "minPrice": 2999,
                "minScore": 0,
                "name": "小米9[拼团-多规格]",
                "numberFav": 46,
                "numberGoodReputation": 2,
                "numberOrders": 33,
                "numberReputation": 0,
                "numberSells": 39,
                "originalPrice": 2999,
                "overseas": false,
                "paixu": 0,
                "persion": 0,
                "pic": "https://cdn.it120.cc/apifactory/2019/06/20/f6e469cd-228d-41e9-95a8-8aad31225117.jpg",
                "pingtuan": true,
                "pingtuanPrice": 1999,
                "propertyIds": ",13090,13093,",
                "recommendStatus": 0,
                "recommendStatusStr": "普通",
                "seckillBuyNumber": 0,
                "sellEnd": false,
                "sellStart": true,
                "shopId": 0,
                "status": 0,
                "statusStr": "上架",
                "storeAlert": false,
                "stores": 81,
                "stores0Unsale": false,
                "storesExt1": 0,
                "storesExt2": 0,
                "tags": "",
                "type": 0,
                "unusefulNumber": 0,
                "usefulNumber": 0,
                "userId": 1605,
                "vetStatus": 1,
                "views": 39826,
                "weight": 0
            }
        ],
        "totalPage": 2,
        "totalRow": 13
    },
    "msg": "success"
};

export default eventHandler(async (event) => {
    return data;
});
