const data = {
    "code": 200,
    "message": "操作成功",
    "data": {
        "advertiseList": [
            {
                "id": 12,
                "name": "小米推荐广告",
                "type": 1,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/xiaomi_banner_01.png",
                "startTime": "2022-11-08T09:04:03.000+00:00",
                "endTime": "2023-11-08T09:04:05.000+00:00",
                "status": 1,
                "clickCount": 0,
                "orderCount": 0,
                "url": "/pages/brand/brandDetail?id=6",
                "sort": 0
            },
            {
                "id": 13,
                "name": "华为推荐广告",
                "type": 1,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/huawei_banner_01.png",
                "startTime": "2022-11-08T09:10:27.000+00:00",
                "endTime": "2023-11-08T09:10:28.000+00:00",
                "status": 1,
                "clickCount": 0,
                "orderCount": 0,
                "url": "/pages/brand/brandDetail?id=3",
                "sort": 0
            },
            {
                "id": 14,
                "name": "苹果推荐广告",
                "type": 1,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/apple_banner_01.png",
                "startTime": "2022-11-08T09:12:54.000+00:00",
                "endTime": "2023-11-08T09:12:55.000+00:00",
                "status": 1,
                "clickCount": 0,
                "orderCount": 0,
                "url": "/pages/brand/brandDetail?id=51",
                "sort": 0
            },
            {
                "id": 15,
                "name": "三星推荐广告",
                "type": 1,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_banner_01.png",
                "startTime": "2022-11-08T09:15:38.000+00:00",
                "endTime": "2023-11-08T09:15:39.000+00:00",
                "status": 1,
                "clickCount": 0,
                "orderCount": 0,
                "url": "/pages/brand/brandDetail?id=2",
                "sort": 0
            },
            {
                "id": 16,
                "name": "OPPO推荐广告",
                "type": 1,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_banner_01.png",
                "startTime": "2022-11-08T09:20:10.000+00:00",
                "endTime": "2023-11-08T09:20:11.000+00:00",
                "status": 1,
                "clickCount": 0,
                "orderCount": 0,
                "url": "/pages/brand/brandDetail?id=21",
                "sort": 0
            }
        ],
        "brandList": [
            {
                "id": 6,
                "name": "小米",
                "firstLetter": "M",
                "sort": 500,
                "factoryStatus": 1,
                "showStatus": 1,
                "productCount": 100,
                "productCommentCount": 100,
                "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/5565f5a2N0b8169ae.jpg",
                "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/xiaomi_banner_01.png"
            },
            {
                "id": 3,
                "name": "华为",
                "firstLetter": "H",
                "sort": 100,
                "factoryStatus": 1,
                "showStatus": 1,
                "productCount": 100,
                "productCommentCount": 100,
                "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/5abf6f26N31658aa2.jpg",
                "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/huawei_banner_01.png"
            },
            {
                "id": 51,
                "name": "苹果",
                "firstLetter": "A",
                "sort": 200,
                "factoryStatus": 1,
                "showStatus": 1,
                "productCount": 55,
                "productCommentCount": 200,
                "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/49b30bb0377030d1.jpg",
                "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/apple_banner_01.png"
            },
            {
                "id": 50,
                "name": "海澜之家",
                "firstLetter": "H",
                "sort": 200,
                "factoryStatus": 1,
                "showStatus": 1,
                "productCount": 66,
                "productCommentCount": 300,
                "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/5a5c69b9N5d6c5696.jpg",
                "bigPic": "http://img10.360buyimg.com/cms/jfs/t1/133148/4/1605/470028/5edaf5ccEd7a687a9/e0a007631361ff75.jpg"
            },
            {
                "id": 21,
                "name": "OPPO",
                "firstLetter": "O",
                "sort": 0,
                "factoryStatus": 1,
                "showStatus": 1,
                "productCount": 88,
                "productCommentCount": 500,
                "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/timg(6).jpg",
                "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_banner_01.png"
            },
            {
                "id": 2,
                "name": "三星",
                "firstLetter": "S",
                "sort": 100,
                "factoryStatus": 1,
                "showStatus": 1,
                "productCount": 100,
                "productCommentCount": 100,
                "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/57201b47N7bf15715.jpg",
                "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_banner_01.png"
            }
        ],
        "homeFlashPromotion": {
            "startTime": "1970-01-01T08:00:00.000+00:00",
            "endTime": "1970-01-01T10:00:00.000+00:00",
            "nextStartTime": "1970-01-01T10:00:00.000+00:00",
            "nextEndTime": "1970-01-01T12:00:00.000+00:00",
            "productList": [
                {
                    "id": 41,
                    "brandId": 6,
                    "productCategoryId": 19,
                    "feightTemplateId": 0,
                    "productAttributeCategoryId": 3,
                    "name": "Redmi K50 天玑8100 2K柔性直屏 OIS光学防抖 67W快充 5500mAh大电量",
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_01.jpg",
                    "productSn": "100035246702",
                    "deleteStatus": 0,
                    "publishStatus": 1,
                    "newStatus": 0,
                    "recommandStatus": 0,
                    "verifyStatus": 0,
                    "sort": 0,
                    "sale": 0,
                    "price": 2099.00,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "usePointLimit": 0,
                    "subTitle": "【品质好物】天玑8100，2K直屏，5500mAh大电量【Note12Pro火热抢购中】 ",
                    "originalPrice": 2099.00,
                    "stock": 1000,
                    "lowStock": 0,
                    "unit": "",
                    "weight": 0.00,
                    "previewStatus": 0,
                    "serviceIds": "",
                    "keywords": "",
                    "note": "",
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_02.jpg",
                    "detailTitle": "",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "brandName": "小米",
                    "productCategoryName": "手机通讯",
                    "description": ""
                },
                {
                    "id": 42,
                    "brandId": 3,
                    "productCategoryId": 19,
                    "feightTemplateId": 0,
                    "productAttributeCategoryId": 3,
                    "name": "HUAWEI Mate 50 直屏旗舰 超光变XMAGE影像 北斗卫星消息",
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/huawei_mate50_01.jpg",
                    "productSn": "100035295081",
                    "deleteStatus": 0,
                    "publishStatus": 1,
                    "newStatus": 0,
                    "recommandStatus": 0,
                    "verifyStatus": 0,
                    "sort": 0,
                    "sale": 0,
                    "price": 4999.00,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "usePointLimit": 0,
                    "subTitle": "【华为Mate50新品上市】内置66W华为充电套装，超光变XMAGE影像,北斗卫星消息，鸿蒙操作系统3.0！立即抢购！华为新品可持续计划，猛戳》 ",
                    "originalPrice": 4999.00,
                    "stock": 1000,
                    "lowStock": 0,
                    "unit": "",
                    "weight": 0.00,
                    "previewStatus": 0,
                    "serviceIds": "",
                    "keywords": "",
                    "note": "",
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/huawei_mate50_02.jpg",
                    "detailTitle": "",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "brandName": "华为",
                    "productCategoryName": "手机通讯",
                    "description": ""
                },
                {
                    "id": 43,
                    "brandId": 1,
                    "productCategoryId": 39,
                    "feightTemplateId": 0,
                    "productAttributeCategoryId": 14,
                    "name": "万和（Vanward)燃气热水器天然气家用四重防冻直流变频节能全新升级增压水伺服恒温高抗风",
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_13L_01.png",
                    "productSn": "10044060351752",
                    "deleteStatus": 0,
                    "publishStatus": 1,
                    "newStatus": 0,
                    "recommandStatus": 0,
                    "verifyStatus": 0,
                    "sort": 0,
                    "sale": 0,
                    "price": 1799.00,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "usePointLimit": 0,
                    "subTitle": "【家电11.11享低价，抢到手价不高于1199】【发布种草秀享好礼！同价11.11买贵补差】爆款超一级能效零冷水】 ",
                    "originalPrice": 1799.00,
                    "stock": 1000,
                    "lowStock": 0,
                    "unit": "",
                    "weight": 0.00,
                    "previewStatus": 0,
                    "serviceIds": "",
                    "keywords": "",
                    "note": "",
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_16L_01.jpg",
                    "detailTitle": "",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "brandName": "万和",
                    "productCategoryName": "厨卫大电",
                    "description": ""
                },
                {
                    "id": 44,
                    "brandId": 2,
                    "productCategoryId": 55,
                    "feightTemplateId": 0,
                    "productAttributeCategoryId": 15,
                    "name": "三星（SAMSUNG）500GB SSD固态硬盘 M.2接口(NVMe协议)",
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_02.jpg",
                    "productSn": "100018768480",
                    "deleteStatus": 0,
                    "publishStatus": 1,
                    "newStatus": 0,
                    "recommandStatus": 0,
                    "verifyStatus": 0,
                    "sort": 0,
                    "sale": 0,
                    "price": 369.00,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "usePointLimit": 0,
                    "subTitle": "【满血无缓存！进店抽百元E卡，部分型号白条三期免息】兼具速度与可靠性！读速高达3500MB/s，全功率模式！点击 ",
                    "originalPrice": 369.00,
                    "stock": 1000,
                    "lowStock": 0,
                    "unit": "",
                    "weight": 0.00,
                    "previewStatus": 0,
                    "serviceIds": "",
                    "keywords": "",
                    "note": "",
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_01.jpg",
                    "detailTitle": "",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "brandName": "三星",
                    "productCategoryName": "硬盘",
                    "description": ""
                },
                {
                    "id": 45,
                    "brandId": 21,
                    "productCategoryId": 19,
                    "feightTemplateId": 0,
                    "productAttributeCategoryId": 3,
                    "name": "OPPO Reno8 8GB+128GB 鸢尾紫 新配色上市 80W超级闪充 5000万水光人像三摄",
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_r8_01.jpg",
                    "productSn": "10052147850350",
                    "deleteStatus": 0,
                    "publishStatus": 1,
                    "newStatus": 0,
                    "recommandStatus": 0,
                    "verifyStatus": 0,
                    "sort": 0,
                    "sale": 0,
                    "price": 2299.00,
                    "promotionPrice": 999.00,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "usePointLimit": 0,
                    "subTitle": "【11.11提前购机享价保，好货不用等，系统申请一键价保补差!】【Reno8Pro爆款优惠】 ",
                    "originalPrice": 2299.00,
                    "stock": 1000,
                    "lowStock": 0,
                    "unit": "",
                    "weight": 0.00,
                    "previewStatus": 0,
                    "serviceIds": "",
                    "keywords": "",
                    "note": "",
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_r8_02.jpg",
                    "detailTitle": "",
                    "promotionStartTime": "2022-11-09T08:15:50.000+00:00",
                    "promotionEndTime": "2022-11-24T16:00:00.000+00:00",
                    "promotionPerLimit": 0,
                    "promotionType": 4,
                    "brandName": "OPPO",
                    "productCategoryName": "手机通讯",
                    "description": ""
                }
            ]
        },
        "newProductList": [
            {
                "id": 40,
                "brandId": 6,
                "productCategoryId": 19,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 3,
                "name": "小米12 Pro 天玑版 天玑9000+处理器 5000万疾速影像 2K超视感屏 120Hz高刷 67W快充",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/xiaomi_12_pro_01.jpg",
                "productSn": "100027789721",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 1,
                "verifyStatus": 0,
                "sort": 0,
                "sale": 0,
                "price": 2999.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "天玑9000+处理器、5160mAh大电量、2KAmoled超视感屏【点击购买小米11Ultra，戳】 ",
                "originalPrice": 2999.00,
                "stock": 500,
                "lowStock": 0,
                "unit": "",
                "weight": 0.00,
                "previewStatus": 0,
                "serviceIds": "",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/xiaomi_12_pro_02.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 4,
                "brandName": "小米",
                "productCategoryName": "手机通讯",
                "description": ""
            },
            {
                "id": 41,
                "brandId": 6,
                "productCategoryId": 19,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 3,
                "name": "Redmi K50 天玑8100 2K柔性直屏 OIS光学防抖 67W快充 5500mAh大电量",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_01.jpg",
                "productSn": "100035246702",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 0,
                "verifyStatus": 0,
                "sort": 0,
                "sale": 0,
                "price": 2099.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "【品质好物】天玑8100，2K直屏，5500mAh大电量【Note12Pro火热抢购中】 ",
                "originalPrice": 2099.00,
                "stock": 1000,
                "lowStock": 0,
                "unit": "",
                "weight": 0.00,
                "previewStatus": 0,
                "serviceIds": "",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_02.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 0,
                "brandName": "小米",
                "productCategoryName": "手机通讯",
                "description": ""
            },
            {
                "id": 39,
                "brandId": 6,
                "productCategoryId": 54,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 13,
                "name": "小米 Xiaomi Book Pro 14 2022 锐龙版 2.8K超清大师屏 高端轻薄笔记本电脑",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_001.jpg",
                "productSn": "100023207945",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 1,
                "verifyStatus": 0,
                "sort": 0,
                "sale": 0,
                "price": 5599.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "【双十一大促来袭】指定型号至高优惠1000，以旧换新至高补贴1000元，晒单赢好礼",
                "originalPrice": 5599.00,
                "stock": 500,
                "lowStock": 0,
                "unit": "",
                "weight": 0.00,
                "previewStatus": 0,
                "serviceIds": "",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_002.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 0,
                "brandName": "小米",
                "productCategoryName": "笔记本",
                "description": ""
            },
            {
                "id": 37,
                "brandId": 51,
                "productCategoryId": 19,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 3,
                "name": "Apple iPhone 14 (A2884) 128GB 支持移动联通电信5G 双卡双待手机",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_001.jpg",
                "productSn": "100038005189",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 0,
                "verifyStatus": 0,
                "sort": 200,
                "sale": 0,
                "price": 5999.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "【11.11大爱超大爱】指定iPhone14产品限时限量领券立减601元！！！部分iPhone产品现货抢购确认收货即送原厂手机壳10元优惠券！！！猛戳 ",
                "originalPrice": 5999.00,
                "stock": 1000,
                "lowStock": 0,
                "unit": "",
                "weight": 208.00,
                "previewStatus": 0,
                "serviceIds": "1,2,3",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_002.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_003.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_004.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 0,
                "brandName": "苹果",
                "productCategoryName": "手机通讯",
                "description": ""
            }
        ],
        "hotProductList": [
            {
                "id": 38,
                "brandId": 51,
                "productCategoryId": 53,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 3,
                "name": "Apple iPad 10.9英寸平板电脑 2022年款",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/ipad_001.jpg",
                "productSn": "100044025833",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 0,
                "verifyStatus": 0,
                "sort": 0,
                "sale": 0,
                "price": 3599.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "【11.11大爱超大爱】iPad9代限量抢购，价格优惠，更享以旧换新至高补贴325元！！快来抢购吧！！ ",
                "originalPrice": 3599.00,
                "stock": 1000,
                "lowStock": 0,
                "unit": "",
                "weight": 0.00,
                "previewStatus": 0,
                "serviceIds": "1,2,3",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/ipad_002.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 0,
                "brandName": "苹果",
                "productCategoryName": "平板电脑",
                "description": ""
            },
            {
                "id": 39,
                "brandId": 6,
                "productCategoryId": 54,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 13,
                "name": "小米 Xiaomi Book Pro 14 2022 锐龙版 2.8K超清大师屏 高端轻薄笔记本电脑",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_001.jpg",
                "productSn": "100023207945",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 1,
                "verifyStatus": 0,
                "sort": 0,
                "sale": 0,
                "price": 5599.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "【双十一大促来袭】指定型号至高优惠1000，以旧换新至高补贴1000元，晒单赢好礼",
                "originalPrice": 5599.00,
                "stock": 500,
                "lowStock": 0,
                "unit": "",
                "weight": 0.00,
                "previewStatus": 0,
                "serviceIds": "",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_002.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 0,
                "brandName": "小米",
                "productCategoryName": "笔记本",
                "description": ""
            },
            {
                "id": 44,
                "brandId": 2,
                "productCategoryId": 55,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 15,
                "name": "三星（SAMSUNG）500GB SSD固态硬盘 M.2接口(NVMe协议)",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_02.jpg",
                "productSn": "100018768480",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 0,
                "verifyStatus": 0,
                "sort": 0,
                "sale": 0,
                "price": 369.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "【满血无缓存！进店抽百元E卡，部分型号白条三期免息】兼具速度与可靠性！读速高达3500MB/s，全功率模式！点击 ",
                "originalPrice": 369.00,
                "stock": 1000,
                "lowStock": 0,
                "unit": "",
                "weight": 0.00,
                "previewStatus": 0,
                "serviceIds": "",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_01.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 0,
                "brandName": "三星",
                "productCategoryName": "硬盘",
                "description": ""
            },
            {
                "id": 43,
                "brandId": 1,
                "productCategoryId": 39,
                "feightTemplateId": 0,
                "productAttributeCategoryId": 14,
                "name": "万和（Vanward)燃气热水器天然气家用四重防冻直流变频节能全新升级增压水伺服恒温高抗风",
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_13L_01.png",
                "productSn": "10044060351752",
                "deleteStatus": 0,
                "publishStatus": 1,
                "newStatus": 0,
                "recommandStatus": 0,
                "verifyStatus": 0,
                "sort": 0,
                "sale": 0,
                "price": 1799.00,
                "giftGrowth": 0,
                "giftPoint": 0,
                "usePointLimit": 0,
                "subTitle": "【家电11.11享低价，抢到手价不高于1199】【发布种草秀享好礼！同价11.11买贵补差】爆款超一级能效零冷水】 ",
                "originalPrice": 1799.00,
                "stock": 1000,
                "lowStock": 0,
                "unit": "",
                "weight": 0.00,
                "previewStatus": 0,
                "serviceIds": "",
                "keywords": "",
                "note": "",
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_16L_01.jpg",
                "detailTitle": "",
                "promotionPerLimit": 0,
                "promotionType": 0,
                "brandName": "万和",
                "productCategoryName": "厨卫大电",
                "description": ""
            }
        ],
        "subjectList": []
    }
}

export default eventHandler(() => {
    return data
})
